### ISSUE TITLE
Update 2_Scope.md with current scope

### ISSUE THREAD

**Issue by jmertic** [carbon-data-specification/Power-Systems-Data#27]
Can you add the current scope of the working group to the 2_Scope.md file? Thanks!

**Comment by gwpicard** [comment]
This is a draft sentence — we will refine and create a PR to update the 2_Scope.md in the repo:

This working group focuses creating a specification for the raw data that can be retrieved from TSO/RTOs... (generation, pricing...) in order to more accurately and systematically account for emissions coming from a grid.

Take some of the language from : https://github.com/carbon-data-specification/Steering_Committee/blob/main/Scope.md

**Comment by pierresegonne** [comment]
Closed by #35
