### ISSUE TITLE
Treatment of timestamps

### ISSUE THREAD

**Issue by m-mirz** [carbon-data-specification/Power-Systems-Data#3]
Initial questions:
- how do we use timestamps in forecasts?
- starting and ending
- which time zone convention do we use

Summary of the discussion below:
- the time stamp marks the beginning of a time interval, e.g. 10:00 describes something that starts at 10:00 and ends at 10:00+X
- for forecasts there are two timestamps: generated at and valid for
- forecast and historical data should not be mixed
- formatting according to ISO 8601: https://en.wikipedia.org/wiki/ISO_8601 (ex. 2022-04-20T16:05:07+00:00)
- timestamps are provided in UTC (as discussed in WG2 meeting)
- for every region the time zone is specified (as discussed in WG2 meeting)

**Comment by grgmiller** [comment]
Thoughts:
- I think there should be two timestamps specified for each piece of data: timestamp in UTC, and timestamp in local time (including daylight saving if applicable). The UTC would provide a standardized timestamp, and the local timestamp would make it easier for users of the data to use in their local TZ without having to worry about the TZ conversions themselves. This also means that we don't have to store separate metadata about the local timezone for users.
- All timestamps should be hour starting, not hour ending: I believe this is more intuitive. If someone sees a timestamp 10:00, it is easier to interpret that this is for all times in hour 10. The hour beginning convention would mean that all timestamps are for hours 0-23 (hour ending convention would require 1-24)

What do we mean by how do we use timestamps in forecasts?

**Comment by gwpicard** [comment]
@grgmiller I'm thinking that timestamps in forecasts means should we have a different format when referring to a specific forecasting horizon.

To illustrate with a scenario:
- Let's say we want a forecast for 2022-04-01 00:00:00
- Now, the forecast for the above could have been generated at T-1 (one-hour time horizon), or at T-12 (twelve-hour time horizon).
- Both of these forecasts are for the same timestamp, but generated for a different time horizon. How do we distinguish between them?

**Comment by Henry-WattTime** [comment]
When we store data for forecasts we have a 'generated at' and and a 'valid for' timestamp. This generally solves the issue.

For timestamps, I think only UTC should be sufficient. This reduces the total data payload and any conversions can be done with any number of libraries. This eliminates the confusion around specifying timezone (although that can be done in the timestamp effectively).

**Comment by grgmiller** [comment]
@gwpicard My thought is that if we are using forecasted data instead of reporting historical data, these should probably be completely separated in different API endpoints or databases. Because in these scenarios, the data are representing different things (i.e. historical data vs hour ahead forecasts vs day ahead forecasts, they probably should not be mixed in the same spot. 

@Henry-WattTime I agree that including TZ info or separate local time info could add a lot of extra data, although it could be helpful potentially depending on the end user. I think it would be important then to specify a separate static table that lists the TZ/DST convention that applies to each BA (or whatever other geographic region the data pertains to). This could help eliminate confusion and serve as a standard reference for converting to local time.

**Comment by Henry-WattTime** [comment]
Should we be adding forecast data fields to the data model? For price, load, generation, etc?

We've seen data straddle multiple timezones (and political boundaries) so assigning a timezone seems arbitrary.  Also, the timestamp itself should always contain timezone data. Any timezone data could exist in a separate static data set? Just like the grid region and generator specific characteristics?

**Comment by grgmiller** [comment]
Also, if we were going to only list data in UTC time and not include a local time column, it would be important to use a datetime format that works well with all major libraries that are used to convert tzs. I've run into formats in published data that libraries like pandas and pytz don't recognize and then you have to do a lot of extra steps to manually manipulate the timestamps

**Comment by Henry-WattTime** [comment]
ISO 8601: https://en.wikipedia.org/wiki/ISO_8601

**Comment by m-mirz** [comment]
@gwpicard @Henry-WattTime @grgmiller I am collecting your thoughts in the first comment in the top. There seem to be already many points where everyone agrees.

**Comment by grgmiller** [comment]
To localize the time again, we want a static attribute associated with the highest level of geographic granularity that identifies the name of the local time zone (and whether that local area follows DST or not). #4 

With regards to understanding if local time follows DST or not, it seems that we maybe need two separate data columns:
 1.  A column to specify the name of the standard time timezone (e.g. "US/Eastern") or the UTC offset (e.g. -5:00)
 2. A column to specify whether the local prevailing time follows DST (could be a binary T/F column)

**Comment by grgmiller** [comment]
Good point. So do you think that specifying a lat/long is enough to then look up the timezone using another library?

I was thinking that if we specify a timezone, we would only do so for the nodal level, instead of for a larger region which may cover multiple timezones.

**Comment by burkaman** [comment]
I see. I would lean towards just including coordinates and letting the user figure out the timezone, but it should be ok to include timezones for units and nodes if we want to have it for usability. 15 US counties have changed their timezone over the last 20 years and the most recent was in 2010, so it's not a huge concern.

I mostly just think that if we have timezones it should be the database name and not the UTC offset, because offsets change more frequently and might change everywhere in 2023.

**Comment by m-mirz** [comment]
@grgmiller is going to prepare a branch with the proposed changes.

**Comment by pierresegonne** [comment]
Closing as https://github.com/carbon-data-specification/Power-Systems-Data/pull/26 was merged
