### ISSUE TITLE
Limit items in the spec to model inputs

### ISSUE THREAD

**Issue by m-mirz** [carbon-data-specification/Power-Systems-Data#5]
Suggestion is to collect power output and emissions data at plant level ideally.

So far, it was proposed to remove from the initial draft:
- weather (input)
- price information (input)
- carbon data (derived)

I merged @Henry-WattTime 's PRs #9 #10 into #16.

**Comment by m-mirz** [comment]
PRs #9  #10 address this issue. I will merge these two branches and create a branch where we can dynamically edit to solve this issue.

**Comment by gwpicard** [comment]
yes, I think we should re-open what was being done in #10 and remove weather by itself first.

In terms of price, I think it is out of scope for the moment and should probably be removed. 

As for carbon, I think it's important to distinguish between two things:
1. system level carbon
2. plant level carbon

The former I think is out of scope because it requires the full specified data model + rules to compute fully. However, I think we should consider keeping the former because it can be tagged as a property to each unit-level plant. What do you think @Henry-WattTime @m-mirz ?

**Comment by gwpicard** [comment]
Captured in spreadsheet (note — excluding weather and derived carbon data):
https://docs.google.com/spreadsheets/d/1ZDYFBX3InzNi4Kwr5_enBc40BwvEnYihd9w0zCr40Uc/edit#gid=0
